import = ["/home/ivoslovacek/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[shell]
args = ["new-session"]
program = "tmux"

[window]
opacity = 0.8
